/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author HP
 */
public class AdminInterface extends javax.swing.JPanel {

    
    public AdminInterface() {
        initComponents();
        ConnectionHandler.updateConnection(wifiButton);
        yesBtn.setVisible(false);
        noBtn.setVisible(false);
        logOffText.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        yesBtn = new javax.swing.JButton();
        noBtn = new javax.swing.JButton();
        logOffText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        viewPatient = new javax.swing.JButton();
        viewDoctors = new javax.swing.JButton();
        viewEmployee = new javax.swing.JButton();
        signOutBtn = new javax.swing.JButton();
        wifiButton = new javax.swing.JButton();
        idList = new java.awt.List();
        nameList = new java.awt.List();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 141, 243));
        jPanel3.setPreferredSize(new java.awt.Dimension(379, 768));

        yesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/logOff1.png"))); // NOI18N
        yesBtn.setBorder(null);
        yesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnActionPerformed(evt);
            }
        });

        noBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/cancel1.png"))); // NOI18N
        noBtn.setBorder(null);
        noBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBtnActionPerformed(evt);
            }
        });

        logOffText.setFont(new java.awt.Font("Sinhala-Lasitha5", 1, 24)); // NOI18N
        logOffText.setForeground(new java.awt.Color(0, 39, 97));
        logOffText.setText("LOGOFF FROM SYSTEM?");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/admin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOffText, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logOffText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 141, 243));

        jPanel2.setBackground(new java.awt.Color(102, 97, 225));

        viewPatient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/patient1.png"))); // NOI18N
        viewPatient.setBorder(null);
        viewPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewPatientMouseExited(evt);
            }
        });
        viewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientActionPerformed(evt);
            }
        });

        viewDoctors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewDoctors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/doc1.png"))); // NOI18N
        viewDoctors.setBorder(null);
        viewDoctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewDoctorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewDoctorsMouseExited(evt);
            }
        });
        viewDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctorsActionPerformed(evt);
            }
        });

        viewEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/emp1.png"))); // NOI18N
        viewEmployee.setBorder(null);
        viewEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewEmployeeMouseExited(evt);
            }
        });
        viewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(viewPatient)
                .addGap(19, 19, 19)
                .addComponent(viewEmployee)
                .addGap(346, 346, 346))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        signOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/backButton.png"))); // NOI18N
        signOutBtn.setBorder(null);
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        wifiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Wifi-Error.png"))); // NOI18N
        wifiButton.setBorder(null);

        idList.setFont(new java.awt.Font("Buxton Sketch", 0, 22)); // NOI18N

        nameList.setFont(new java.awt.Font("Buxton Sketch", 0, 22)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(idList, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(nameList, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(signOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(wifiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wifiButton))
                .addGap(51, 51, 51)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameList, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(idList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnActionPerformed
        if(evt.getSource()== yesBtn){
            HospitalManagementSystem.update(this ,new LoginPageGUI());
        }
    }//GEN-LAST:event_yesBtnActionPerformed

    private void noBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBtnActionPerformed
        if (evt.getSource() == noBtn) {
            yesBtn.setVisible(false);
            noBtn.setVisible(false);
            logOffText.setVisible(false);
        }
    }//GEN-LAST:event_noBtnActionPerformed

    private void viewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientActionPerformed
        if(evt.getSource()== viewPatient){
            idList.removeAll();
            nameList.removeAll();
            ConnectionHandler.updateConnection(wifiButton);
            try {
                ResultSet result = new Admin().viewPatientDetails();
                while(result.next()){
                    idList.add(result.getString(1));
                    nameList.add(result.getString(2));
                }
            }
            catch(SQLException | NullPointerException ex) {}
        }
    }//GEN-LAST:event_viewPatientActionPerformed

    private void viewDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDoctorsActionPerformed
        if(evt.getSource()== viewDoctors){
            idList.removeAll();
            nameList.removeAll();
            ConnectionHandler.updateConnection(wifiButton);
            try {
                ResultSet result = new Admin().viewDoctorDetails();
                while(result.next()){
                    idList.add(result.getString(1));
                    nameList.add(result.getString(2));
                }
            }
            catch(SQLException | NullPointerException ex) {}
        }
    }//GEN-LAST:event_viewDoctorsActionPerformed

    private void viewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeActionPerformed
        if(evt.getSource()== viewEmployee){
            idList.removeAll();
            nameList.removeAll();
            ConnectionHandler.updateConnection(wifiButton);
            try {
                ResultSet result = new Admin().viewEmployeeDetails();
                while(result.next()){
                    idList.add(result.getString(1));
                    nameList.add(result.getString(2));
                }
            }
            catch(SQLException | NullPointerException ex) {}
        }
    }//GEN-LAST:event_viewEmployeeActionPerformed

    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        if(evt.getSource()== signOutBtn){
            yesBtn.setVisible(true);
            noBtn.setVisible(true);
            logOffText.setVisible(true);
        }
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void viewDoctorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDoctorsMouseEntered
        if(evt.getSource()== viewDoctors){
            viewDoctors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/doc2.png")));
        }
    }//GEN-LAST:event_viewDoctorsMouseEntered

    private void viewDoctorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDoctorsMouseExited
        if(evt.getSource()== viewDoctors){
            viewDoctors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/doc1.png")));
        }
    }//GEN-LAST:event_viewDoctorsMouseExited

    private void viewPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPatientMouseEntered
        if(evt.getSource()== viewPatient){
            viewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/patient2.png")));
        }
    }//GEN-LAST:event_viewPatientMouseEntered

    private void viewPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPatientMouseExited
        if(evt.getSource()== viewPatient){
            viewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/patient1.png")));
        }
    }//GEN-LAST:event_viewPatientMouseExited

    private void viewEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmployeeMouseEntered
        if(evt.getSource()== viewEmployee){
            viewEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/emp2.png")));
        }
    }//GEN-LAST:event_viewEmployeeMouseEntered

    private void viewEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmployeeMouseExited
        if(evt.getSource()== viewEmployee){
            viewEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/emp1.png")));
        }
    }//GEN-LAST:event_viewEmployeeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List idList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logOffText;
    private java.awt.List nameList;
    private javax.swing.JButton noBtn;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JButton viewDoctors;
    private javax.swing.JButton viewEmployee;
    private javax.swing.JButton viewPatient;
    private javax.swing.JButton wifiButton;
    private javax.swing.JButton yesBtn;
    // End of variables declaration//GEN-END:variables
}
