/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class RemoveDoctor extends javax.swing.JPanel {

    /**
     * Creates new form RemoveDoctor
     */
    public RemoveDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        docNumTxt = new javax.swing.JTextField();
        docIdTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        availabilityLbl = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Remove Using NID");
        add(jLabel1);
        jLabel1.setBounds(320, 60, 224, 16);

        jLabel2.setText("Remove Using doctor number");
        add(jLabel2);
        jLabel2.setBounds(330, 200, 224, 16);

        jLabel3.setText("Doctor NID");
        add(jLabel3);
        jLabel3.setBounds(190, 110, 61, 16);

        jLabel4.setText("Doctor number");
        add(jLabel4);
        jLabel4.setBounds(180, 270, 85, 27);
        add(docNumTxt);
        docNumTxt.setBounds(360, 260, 267, 37);
        add(docIdTxt);
        docIdTxt.setBounds(360, 100, 267, 37);

        jButton1.setText("Search Availability");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(660, 170, 150, 33);

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(930, 470, 105, 33);
        add(availabilityLbl);
        availabilityLbl.setBounds(850, 160, 150, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // search request
        String availability = "";
        String id = docIdTxt.getText();
        String dNum = docNumTxt.getText();
        if(id==null && dNum ==null){
            infoBox("No data entered!","At least one box need to be filled!");
        }
        availabilityLbl.setText(availability);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabilityLbl;
    private javax.swing.JTextField docIdTxt;
    private javax.swing.JTextField docNumTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }

}
