/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class RemoveDoctorGUI extends javax.swing.JPanel {

    /**
     * Creates new form RemoveDoctor
     */
    private String permId=null;
    public RemoveDoctorGUI() {
        initComponents();
        ConnectionHandler.updateConnection(wifiButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        docIdTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        availabilityLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        wifiButton = new javax.swing.JButton();
        wifiButton1 = new javax.swing.JButton();
        availableDocTxt = new javax.swing.JTextField();
        quitBtn = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Remove Using NID");
        add(jLabel1);
        jLabel1.setBounds(280, 170, 224, 16);

        jLabel3.setText("Doctor NID");
        add(jLabel3);
        jLabel3.setBounds(180, 250, 61, 16);
        add(docIdTxt);
        docIdTxt.setBounds(360, 240, 267, 37);

        searchBtn.setText("Search Availability");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn);
        searchBtn.setBounds(590, 390, 150, 33);

        editBtn.setText("Remove");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        add(editBtn);
        editBtn.setBounds(1160, 680, 105, 33);
        add(availabilityLbl);
        availabilityLbl.setBounds(850, 160, 150, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/backButton.png"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(20, 20, 41, 41);

        wifiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Wifi-Error.png"))); // NOI18N
        wifiButton.setBorder(null);
        add(wifiButton);
        wifiButton.setBounds(20, 20, 41, 41);

        wifiButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/Wifi-Error.png"))); // NOI18N
        wifiButton1.setBorder(null);
        add(wifiButton1);
        wifiButton1.setBounds(80, 20, 41, 41);

        availableDocTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableDocTxtActionPerformed(evt);
            }
        });
        add(availableDocTxt);
        availableDocTxt.setBounds(240, 440, 240, 40);

        quitBtn.setText("quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });
        add(quitBtn);
        quitBtn.setBounds(1129, 30, 110, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // search request
        String availability = "";
        String id = docIdTxt.getText().trim();
        
        if("".equals(id) ){
            infoBox("No data entered!","Docctor nic needs to be filled!");
        }
        else{
            availability=new RemoveDoctor().searchAvailability(id);
        }
        this.permId=id;
        availabilityLbl.setText(availability);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if(permId!=null)
        new RemoveDoctor().removeDoctor(permId);
        else{
        new RemoveDoctor().removeDoctor(docIdTxt.getText().trim());
        }
            
    }//GEN-LAST:event_editBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if(evt.getSource()== backBtn){
           HospitalManagementSystem.update(this ,new HRStaffInterface());
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void availableDocTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableDocTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableDocTxtActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabilityLbl;
    private javax.swing.JTextField availableDocTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField docIdTxt;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton wifiButton;
    private javax.swing.JButton wifiButton1;
    // End of variables declaration//GEN-END:variables
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }

}
